name: 🧩 Feature
description: New functionalities to be developed
title: "|"
type: "Feature 🧩"
projects: ["StaytunedLLP/43"]

body:
  - type: markdown
    attributes:
      value: |
        :yellow_circle: **CAUTION**  
        1. The future is AI. Embrace it, or be left behind. :robot:   
        1. Search existing issues first to avoid duplicates. :dancing_women:  

        :red_circle: **IMPORTANT**  
        1. First flag it, then ship it with confidence! :white_flag:  
        1. Your insights matter! Report issues to drive a change. :pushpin:   

        Add [alert](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts) if needed.

  - type: textarea
    id: Purpose
    attributes:
      label: Purpose
      description: |
        The "why" behind the issue - the problem to be solved or the opportunity to be seized.
    validations:
      required: true

  - type: textarea
    id: Outcome
    attributes:
      label: Outcome
      description: |
        The desired end result - the positive change or benefit that will be achieved.
    validations:
      required: true

  - type: textarea
    id: Background
    attributes:
      label: Background
      description: |
        The context or relevant information needed to understand the issue.
    validations:
      required: true

  - type: textarea
    id: Actions
    attributes:
      label: Actions
      description: |
        The specific tasks or steps required to resolve the issue and achieve the desired outcome.
    validations:
      required: true